file = open("output.txt", "r")

line1 = file.readline()
line2 = file.readline()
line3 = file.readline()
line4 = file.readline()
line5 = file.readline()
line6 = file.readline()
line7 = file.readline()
line8 = file.readline()
line9 = file.readline()
line10 = file.readline()

print("Line 1:", line1, end="")
print("Line 2:", line2, end="")
print("Line 3:", line3, end="")
print("Line 4:", line4, end="")
print("Line 5:", line5, end="")
print("Line 6:", line6, end="")
print("Line 7:", line7, end="")
print("Line 8:", line8, end="")
print("Line 9:", line9, end="")
print("Line 10:", line10, end="")

file.close()